### ISSUE TITLE
Possible incorrect implementation of cross correlation

### ISSUE THREAD

**Issue by Camotubi** [liebharc/basic_dsp#42]
Hi again, I tried running the [cross-correlation example](https://liebharc.github.io/basic_dsp/basic_dsp/trait.CrossCorrelationArgumentOps.html) and it runs fine.
The issue is that when I try computing the cross correlation in `gnu octave` with `xcorr` from the `signal `pakage. I get a different but similar result. i + 1 value from gnu octave match with i values of the expected vector from the example.

It is possible that I'm interpreting wrongly either gnu octave or your library. 
If you could give me some guidance. I'll be very grateful.

![2019-02-14-164738_912x256_scrot](https://user-images.githubusercontent.com/4031324/52819856-6af28c00-3078-11e9-86b3-4362c77af7ce.png)
Expected output according to the example: [2.0, 0.0, 8.0, 0.0, 20.0, 0.0, 24.0, 0.0, 18.0, 0.0]

**Comment by liebharc** [comment]
Hi again, so I only have my phone with me which makes it harder to put things together. But lets try one thing: If to_complex_time_vec is called on a vector it assumes complex interleaved format, basically pairs of real and imag parts. So the octave analog to the first vector in the corr example would be 1+i,2+2i,3+3i (and the other vector accordingly). In your Octave code you are interpreting the vectors as pure real valued, so that should explain at least some differences. Could you please try that and respond back how that changes the results?

As a note: There are several other conversion functions, but the complex interleaved format is the internal format of the lib for complex data so the conversion is cheap. And thanks for verifying results, it's good if people do that.

Am 15. Februar 2019 11:01:49 GMT+13:00 schrieb "Carlos Tuñón" <notifications@github.com>:

**Comment by Camotubi** [comment]
I knew that I was doing something wrong.
![2019-02-15-173242_609x381_scrot](https://user-images.githubusercontent.com/4031324/52887987-e0795d80-3147-11e9-9443-8caea659c777.png)
But, I would argue that the output of the function is not clear. Could it return a Vec\<Complex\> from num-complex instead? ( I'm talking from the UX point of view, I know that is easy to convert from my end😅).
Anyway, thanks for your time dude. Enjoy your vacation!!!
(\~‾▿‾)\~
