### ISSUE TITLE
points vs data when using interpolatei

### ISSUE THREAD

**Issue by csheaff** [liebharc/basic_dsp#46]
Hi,

Running the following:

```
let mut dsp_vec = vec![0.0; 1000].to_real_time_vec();
let mut buffer = SingleBuffer::new();
dsp_vec.interpolatei(&mut buffer, &RaisedCosineFunction::new(0.35), 2).unwrap();
let (vec, points) = dsp_vec.get();
println!("{:?}", vec.len());
println!("{:?}", points);
```

yields:

```
4000
2000
```

I was expecting `vec.len() = 2000`. I see that the vector length can be twice the number points in the case of complex data, but that is not the case here. Could some explanation be provided? Apologies if this is quite basic and I'm just missing something.

**Comment by liebharc** [comment]
Hi,

Thanks for pointing this out. I had a quick look at the code. Internally this interpolation is always done on complex data. The result is at the end calculated back into real numbers, but it seems at the end it's missed to note the correct array length. As a workaround you should be able to disregard all data beyond vec.len(). I'll look into this further then and release a fix.

**Comment by liebharc** [comment]
Hi,

Thanks for pointing this out. I had a quick look at the code. Internally this interpolation is always done on complex data. The result is at the end calculated back into real numbers, ~~but it seems at the end it's missed to note the correct array length. As a workaround you should be able to disregard all data beyond vec.len(). I'll look into this further then and release a fix.~~

**Update**: I would correct what I said earlier:

```
        let mut dsp_vec = vec![0.0; 1000].to_real_time_vec();
        let mut buffer = SingleBuffer::new();
        dsp_vec.interpolatei(&mut buffer, &RaisedCosineFunction::new(0.35), 2).unwrap();
        assert_eq!(dsp_vec.len(), 2000);
        assert_eq!(dsp_vec.points(), 2000);
        let (vec, points) = dsp_vec.get();
        assert_eq!(points, 2000);
        assert_eq!(vec.len(), 4000);
```` 
So the DspVecs `len` and `points` are correct. The reason why `vec.len()` is at 4000 is because for the interpolation with complex numbers it had to reserve the extra space. So it "leaks" internal details here and the reason for that is that you can create a DspVec based on other data types than a vec. One example are arrays and you can't truncate them without copying them (plus if the code is executed in a loop then the API provides means to avoid repeated memory frees/allocations). I will check if it's possible to specialize the `DspVec.get` method to truncate the vector. Until then you could add the truncate call yourself:

```
        let mut dsp_vec = vec![0.0; 1000].to_real_time_vec();
        let mut buffer = SingleBuffer::new();
        dsp_vec.interpolatei(&mut buffer, &RaisedCosineFunction::new(0.35), 2).unwrap();
        let (mut vec, points) = dsp_vec.get();
        vec.truncate(points);
        assert_eq!(vec.len(), 2000);
```

**Comment by csheaff** [comment]
Thanks for clearing this up.

**Comment by liebharc** [comment]
So since the conversion between a `DspVec` to a `Vec` is safe I think a good solution is to implement the `From` trait for this case:

```
let mut dsp_vec = vec![0.0; 1000].to_real_time_vec();
let mut buffer = SingleBuffer::new();
dsp_vec.interpolatei(&mut buffer, &RaisedCosineFunction::new(0.35), 2).unwrap();
let vec: Vec<f64> = dsp_vec.into();
assert_eq!(vec.len(), 2000);
```

The change will be part of the next release.
